apiVersion: batch/v1
kind: Job
metadata:
  name: toolbox
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: toolbox
        image: quay.io/redhat/3scale-toolbox:master
        imagePullPolicy: Always
        args: [ "3scale", "import", "openapi", "-d", "rmendes-instance-a", "/artifacts/swagger.json", "--override-private-base-url=https://echo-api.3scale.net", "-t", "beer-catalog", "-k" ]
        env:
        - name: HOME
          value: /config
        volumeMounts:
        - name: toolbox-config
          mountPath: /config
        - name: artifacts
          mountPath: /artifacts
      volumes: 
      - name: toolbox-config
        secret: 
          secretName: 3scale-toolbox
      - name: artifacts
        configMap: 
          name: openapi
